theme:
  name: readthedocs
  custom_dir: 'custom_theme/'
site_name: MBINCompiler
site_dir: html_docs/site/
nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - libMBIN:
      - Usage: libmbin\usage.md
        