theme:
  name: readthedocs
  custom_dir: 'docs/custom_theme/'
  highlightjs: true
  hljs_languages:
    - c#
site_name: MBINCompiler
site_dir: html_docs/site/
nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - libMBIN:
      - Usage: libmbin\usage.md
        