name: MBINCompiler

on:
  # Run on all branches except for the gh-pages branch
  push:
    branches:
      - development
  pull_request:
    branches-ignore:
      - 'gh-pages'
  create:

jobs:
  build:
    name: Build and test MBINCompiler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.x'
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Build Windows binary
        run: |
          dotnet restore
          dotnet build -r win-x64 -p:Configuration=Release /nowarn:cs0618
      - name: Build linux binary
        run: |
          dotnet restore
          dotnet build -r ubuntu.16.04-x64 -p:Configuration=Release /nowarn:cs0618
      - name: Make binary executable
        run: sudo chmod +x Build/Release/ubuntu.16.04-x64/MBINCompiler.exe
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests mkdocs==1.0.4
      - name: Run tests
        run: python -m pytest --platform ubuntu.16.04-x64 --tb=no --report
      - name: Upload binary for release
        uses: actions/upload-artifact@v2
        with:
          name: MBINCompiler
          path: |
            Build/Release/win-x64/MBINCompiler.exe
            Build/Release/ubuntu.16.04-x64/MBINCompiler.exe
            Build/Release/libMBIN.dll
            report.json
  release:
    name: Release MBINCompiler binaries and other data
    # Only run this job if the commit was tagged.
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download files for release
        uses: actions/download-artifact@v2
        with:
          name: MBINCompiler
      - name: Get MBINCompiler tag version
        run: |
          echo "VERSION=$(sudo mono Build/Release/ubuntu.16.04-x64/MBINCompiler.exe version | awk '{print $2}')" >> $GITHUB_ENV
          echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Upload resources if version matches
        if: env.VERSION == env.TAG
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ env.TAG }} release"
          tag_name: ${{ env.TAG }}
          files: |
            Build/Release/win-x64/MBINCompiler.exe
            Build/Release/libMBIN.dll
            report.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if tag doesn't match version
        if: env.VERSION != env.TAG
        run: |
          echo "There is a version mismatch between the tag and MBINCompiler version!"
          exit 1
